{% set name = "yaqc-bluesky" %}
{% set version = "2021.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 42054e20639b16c583dea93de1959fe821163dedf21e8d9c69bafc77ca563c19

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - yaqc >=2020.7.3
    - python >=3.8
  run:
    - yaqc >=2020.7.3
    - python >=3.8

test:
  imports:
    - yaqc_bluesky
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bluesky/yaqc-bluesky
  summary: A bluesky interface to the yaq instrument control framework.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
